### ISSUE TITLE
css 中的background

### ISSUE THREAD

**Issue by smallwebbird** [smallwebbird/blogs#24]
background-position默认的图片的位置，从元素的左上角开始的，所以这时我们如果想要改变背景图片的位置，就可以使用这个图片，这也就是雪碧图所用的原理,看下图
![tim 20181206184403](https://user-images.githubusercontent.com/28871189/49579371-ff5cb600-f986-11e8-9b35-aafb03e321b7.png)
可以看出默认背景图片是从左上角开始的，我现在想把眼睛的位置移动到绿色框内我们就可以使用如下代码实现
```css
{
  width: 500px;
 height: 300px;
 border: 1px solid red;
background: url(./xiao.jpg);			
background-repeat: no-repeat;
background-position: -80px -30px;
}
```
![tim 20181206184822](https://user-images.githubusercontent.com/28871189/49579556-8742c000-f987-11e8-9749-d5e6eb237a84.png)
负数代表着向左和向上移动背景图片
我们在来看一下background-origin的属性，把背景图片定位到内容框中，内边距框和边框
使用如下代码能够为padding区域设置背景
```css
{
width: 150px;
height: 150px;
border: 1px solid red;
padding:50px;
background: url(./b.jpg);			
background-repeat: no-repeat;
background-origin: padding-box;
}
```
background-attachment属性用来描述背景图片是否根据浏览器的滚动的滚动而滚动，默认使滚动的
它有俩个属性值，fixed，scroll，fixed背景图片不随滚动而滚动，scroll随着滚动而滚动，它是默认值
