### ISSUE TITLE
你真的懂opacity

### ISSUE THREAD

**Issue by smallwebbird** [smallwebbird/blogs#28]
我们先上代码
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        .wrap{
            width: 500px;
            height: 500px;
            border: 1px solid red;
        }
        .same{
            width: 100px;
            height: 100px;
        }
        .one{
            background: green;
        }
        .two{
            background: red;
            margin: -40px 0 0 40px; 
        }
        .three{
            background: blue;
            margin: -40px 0 0 80px;
        }
    </style>
</head>
<body>
    <div class="wrap">
        <div class="same one"></div>
        <div class="same two"></div>
        <div class="same three"></div>
    </div>
</body>
</html>
```
然后我们看一下效果
![tim 20181211173126](https://user-images.githubusercontent.com/28871189/49791069-9d2af900-fd6a-11e8-8478-034909638160.png)
然后我们修改以下样式
```css
 .two{
            background: red;
            margin: -40px 0 0 40px; 
            opacity: 0.5;
        }
```
然后我们看一下效果
![tim 20181211173310](https://user-images.githubusercontent.com/28871189/49791280-1cb8c800-fd6b-11e8-8725-8b71e0257ae4.png)
我们发现第二个div，覆盖了第一个和第三个，就好像设置了z-index一样，我们在设置以下样式
```css
.three{
 background: blue;
 margin: -40px 0 0 80px;
postion:relative;
z-index:`100;
}
```
我们在重新看一下效果
![tim 20181211173947](https://user-images.githubusercontent.com/28871189/49791594-c5ffbe00-fd6b-11e8-8334-ebc178fea3da.png)
又恢复了正常的层级关系
然后我们看一下rgba设置透明度和opacity相同吗
设置如下样式
```css
 .one{
            background: green;
        }
        .two{
            background: rgba(0, 0, 0, 0.5);
            margin: -40px 0 0 40px; 
        }
        .three{
            background: blue;
            margin: -40px 0 0 80px;
        }
```
然后我们看一下效果
![tim 20181211174315](https://user-images.githubusercontent.com/28871189/49791852-49211400-fd6c-11e8-9e2c-1071547f14b1.png)
我们发现rgba不存在这种问题
这个问题最近准备写一个遮屏效果，然后在遮屏元素中有一个子元素，子元素上显示相关内容，为遮屏元素设置opacity，然后发现一只遮盖子元素，按理说设置z-index的父元素的层级总是比子元素低，除非子元素的z-index为负数，然后才发现是opacity在搞鬼，遮屏效果图
![tim 20181211174707](https://user-images.githubusercontent.com/28871189/49792078-d19fb480-fd6c-11e8-97fe-579d498cbc68.png)
